name: Build, Tag, and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the "main" branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build the Docker Image with a Custom Name
      - name: Build Docker Image
        run: docker build -t my-image:latest .
      - name: List Docker Images
        run: docker images

      - name: Debug Secret Retrieval
        run: echo "${{ secrets.DOCKER_USERNAME }}"


      # Step 4: Tag the Image for Docker Hub
      - name: Tag Docker Image
        run: docker tag my-image:latest docker.io/sauravkursing/testing:latest


      # Step 5: Push the Tagged Image to Docker Hub
      - name: Push Docker Image
        run: docker push sauravkursing/testing:latest
